#!/usr/bin/with-contenv bash

location=`find /app -name "angular.json" -maxdepth 2`

if [ -z "$location" ]; then
	cd /app || exit
	mv /defaults/helloworld /app/
else
	cd ${location:0:-12} || exit
fi

exec /usr/bin/ng serve
